// ================================================
// CryptoFish â€” bio.js
// Fish biography system:
//   1. Wikipedia REST API (CORS-enabled, no key)
//   2. Rich genus-ecology fallback
//   3. Hand-written honorary bios
// ================================================

const _bioCache = new Map();

// Safe HTML escape â€” bio.js loads before app.js, so we need this here.
// app.js also declares escapeHTML (identical logic); the function declaration there
// will simply overwrite this one at parse time â€” no conflict.
function escapeHTML(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// â”€â”€ Honorary bios (crypto/NFT community members) â”€â”€
const HONORARY_BIOS = {
  'BeardedKsum':      'BeardedKsum is one of the earliest collectors of CryptoFish, known in the NFT community for their sharp eye for fish-based and nature-themed digital art. Their token #1 was personally issued by Findurnemo as a recognition of being the very first supporter of the project.',
  'Ricky Disco':      'Ricky Disco is a longtime community member and early CryptoFish collector whose enthusiastic support helped establish the collection\'s initial community. Known for their energetic presence in NFT circles, Ricky received this honorary token as a symbol of that early commitment.',
  'DeMemeTree':       'DeMemeTree is a crypto and NFT community personality known for meme culture and early support of independent digital artists. This honorary token was created by Findurnemo in recognition of their role in spreading awareness of the CryptoFish project.',
  'DJ Connor Buntain': 'DJ Connor Buntain is a music artist and DJ who bridged the worlds of music and NFTs. An early adopter of digital collectibles, Connor\'s passion for art and culture led to this personal CryptoFish honorary â€” one of the few tokens with a music connection in the collection.',
  '3XDIEGO':          '3XDIEGO is a collector and creator active in the NFT ecosystem, known for their consistent involvement in independent and science-adjacent NFT projects. This honorary was created for them by Findurnemo as acknowledgment of meaningful early support.',
  'Blue Dinosaurs':   'Blue Dinosaurs is an NFT project and community entity that engaged with the CryptoFish collection from its earliest days. The honorary token reflects a cross-community connection between two projects sharing themes of rare, illustrated creatures.',
  'Della Jonny':      'Della Jonny is a community member and collector honored for their personal support of Findurnemo\'s work. Their honorary CryptoFish token was created as a one-of-a-kind recognition of a meaningful relationship within the project\'s early community.',
  'Pancake':          'Pancake is a beloved nickname in the CryptoFish Discord, given to a community member whose warm personality and consistent presence helped shape the tone of the early collector group. This token was a personal thank-you from Findurnemo.',
  'Sleek':            'Sleek is an early CryptoFish community member known for clean aesthetics and a genuine appreciation of the taxonomic depth behind the collection. Their honorary token reflects a friendship forged in the earliest days of the project.',
  'Kennfth':          'Kennfth is a collector and advocate for CryptoFish whose token comes paired with an actual scientific specimen â€” Apistogramma baenschi from the Rio Huallaga system in Peru. The dual nature of this token (community honorary + real species) makes it one of the most unique in the collection.',
  'AltcoinMurphy':    'AltcoinMurphy is a well-known crypto commentator and NFT community member who covers altcoin markets and independent digital art projects. Their honorary CryptoFish was issued by Findurnemo as recognition of cross-community support and genuine enthusiasm for the project\'s scientific angle.',
  'Duckdive':         'Duckdive is a collector and ocean-culture enthusiast whose handle reflects a love of diving and underwater life â€” making them a natural fit for an honorary CryptoFish. Findurnemo created this token as a personal tribute to a kindred spirit.',
  'Offgridgecko':     'Offgridgecko is a community member with a distinctive off-grid, nature-first philosophy that resonated deeply with CryptoFish\'s conservation themes. This honorary token was issued as an acknowledgment of that shared value system.',
  'Ghost Friend':     'Ghost Friend is the handle of a community member known for quiet but deeply felt support of the CryptoFish project. Their animated honorary token â€” one of the few GIFs in the collection â€” was a creative tribute from Findurnemo.',
  'DigitalfilmNO':    'DigitalfilmNO is a Norwegian digital filmmaker and NFT creator whose work spans documentary, digital art, and blockchain culture. Their CryptoFish honorary token, depicted as "Linda," represents a personal connection to Findurnemo and the Scandinavian NFT community.',
  'B33F':             'B33F is a collector and NFT culture participant known for their direct style and honest engagement in community spaces. Their honorary CryptoFish was issued as a personal recognition of straightforward, no-hype support for the project.',
  'Captain Hamster':  'Captain Hamster is a community personality whose whimsical handle belies a serious appreciation for biology-based digital art. One of the more memorable characters in the CryptoFish Discord, their honorary token became an instant fan favorite.',
  'Thaddeus':         'Thaddeus\'s honorary token is depicted as Eretmochelys imbricata â€” the Critically Endangered hawksbill sea turtle â€” one of the most ecologically significant animals ever featured in the CryptoFish collection. The choice was deliberate: Findurnemo selected this species to honor a person whose care for living things extends beyond the screen.',
  'Bizzy':            'Bizzy is a collector and creative active in both the NFT space and broader digital culture. This honorary token was created by Findurnemo as a personal tribute to someone whose energy and enthusiasm helped accelerate the early growth of the CryptoFish community.',
  'Armen':            'Armen is an early collector and longtime CryptoFish community member. Their honorary token is a direct expression of gratitude from Findurnemo â€” a one-of-a-kind piece acknowledging someone who was present from the very beginning.'
};

// â”€â”€ Genus ecology knowledge base â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Each entry is used when Wikipedia has no article or returns a stub.
// Fields: fam (family), type (ecological type), habitat, feeding, behavior, notes, depth (optional)
const GENUS_ECOLOGY = {

  // â”€â”€ Lake Malawi cichlids: mbuna (rock-dwellers) â”€â”€
  'Metriaclima':    { fam:'Cichlidae', type:'mbuna cichlid', habitat:'rocky littoral shoreline of Lake Malawi at depths of 2â€“15 m', feeding:'scrapes epilithic algae (aufwuchs) from rock faces using an incisor-like dentition', behavior:'highly territorial; males defend small rock territories and display vivid electric-blue or barred coloration to attract females; maternal mouthbrooders', notes:'among the most speciated vertebrate genera on Earth; populations at different offshore rocky outcrops evolve isolation and color divergence rapidly, making each locality a potential distinct taxon' },
  'Pseudotropheus': { fam:'Cichlidae', type:'mbuna cichlid', habitat:'rock-sand interface zones in Lake Malawi, from the surface down to 40 m', feeding:'scrapes algae from rocks; some populations supplement with invertebrates and zooplankton depending on locality depth', behavior:'intensely aggressive intraspecifically; males chase rivals constantly; color varies dramatically between populations separated by only a few kilometers of sand', notes:'the name literally means "false Tropheus," reflecting early taxonomic confusion with Tanganyikan forms; the genus has been extensively revised and many former Pseudotropheus are now placed in Metriaclima, Maylandia, and Chindongo' },
  'Melanochromis':  { fam:'Cichlidae', type:'mbuna cichlid', habitat:'upper rocky shoreline of Lake Malawi, typically 1â€“10 m', feeding:'opportunistic; scrapes algae, picks invertebrates, and will eat other fish\'s eggs and fry when opportunity arises', behavior:'among the most aggressive of all mbuna; extreme sexual dichromatism with males often jet-black with white horizontal stripes and females yellow-orange; females sometimes more dangerous than males', notes:'notorious for hybridizing with other mbuna in aquaria; endemic to Lake Malawi and its satellite systems; some species endemic to single islands' },
  'Cynotilapia':    { fam:'Cichlidae', type:'mbuna cichlid', habitat:'transitional zones between rocky and open water in Lake Malawi, 5â€“30 m', feeding:'zooplanktivore; picks zooplankton from the water column using unicuspid (single-cusped) teeth that distinguish it from other mbuna', behavior:'less territorial than algae-grazing mbuna; forms loose aggregations above rocky habitat; less sexually dichromatic than rock-scraping relatives', notes:'the genus name refers to their "dog teeth" â€” the unicuspid dentition is an adaptation to open-water planktivory unusual for a rock-associated cichlid' },
  'Labidochromis':  { fam:'Cichlidae', type:'mbuna cichlid', habitat:'rocky shoreline of Lake Malawi at 5â€“30 m; commonly associated with Vallisneria beds in shallower areas', feeding:'picks insects, snails, and invertebrates from rock crevices; the narrow, forceps-like jaw is suited for extracting prey from tight spaces', behavior:'far less aggressive than other mbuna; the popular "electric yellow" morph (L. caeruleus) is one of the most kept cichlids worldwide; generally compatible with other species in captivity', notes:'relatively gentle temperament compared to most mbuna; their narrow jaw gave the genus its name (labidochromis = "forceps-colored fish")' },
  'Labeotropheus':  { fam:'Cichlidae', type:'mbuna cichlid', habitat:'surge zones and steep rocky walls of Lake Malawi, shallow to 20 m', feeding:'hyper-specialized algae scraper; a downward-pointing, fleshy snout overhangs the mouth to press against near-vertical rock faces while thick lips protect the jaw', behavior:'one of the most specialized mbuna; males can be extremely aggressive; one of few cichlids with a large robust body adapted for clinging to wave-swept rock faces', notes:'the fleshy rostral lobe is unique among cichlids and allows grazing at angles impossible for other mbuna; some of the most spectacular male coloration in the lake occurs in this genus' },
  'Iodotropheus':   { fam:'Cichlidae', type:'mbuna cichlid', habitat:'rocky shores of southern Lake Malawi, typically 3â€“20 m', feeding:'scrapes algae from rock; also ingests invertebrates associated with aufwuchs communities', behavior:'known for its muted rusty-brown/lavender coloration, unusual among mbuna; relatively peaceful for mbuna; maternal mouthbrooder', notes:'one of the few non-cichlid-colored mbuna; the "rusty cichlid" is notable for its unusual brownish-violet hue rather than the blues and yellows typical of the lake' },
  'Chindongo':      { fam:'Cichlidae', type:'mbuna cichlid', habitat:'rocky shores of Lake Malawi', feeding:'algae scraper and aufwuchs grazer', behavior:'many species recently reclassified from Pseudotropheus; morphologically and behaviorally similar to related mbuna genera', notes:'the name was resurrected in 2016 when molecular phylogenetics confirmed this group as distinct from Pseudotropheus; one of the cleaner examples of modern cichlid taxonomy' },
  'Genyochromis':   { fam:'Cichlidae', type:'scale-eating mbuna', habitat:'rocky shores of Lake Malawi', feeding:'lepidophage (scale-eater); uses powerful jaws to scrape scales from other fish in a highly specialized predatory strategy', behavior:'mimics the behavior of benign species to approach prey; one of very few scale-eating cichlids on Earth', notes:'one of the most extreme dietary specialists in Lake Malawi; the scale-eating habit has evolved independently multiple times across African Great Lakes cichlids' },
  'Petrotilapia':   { fam:'Cichlidae', type:'mbuna cichlid', habitat:'rocky surge zones, Lake Malawi', feeding:'grazes algae; one of the largest mbuna, reaching 20+ cm, giving it access to territory other mbuna cannot hold', behavior:'males defend large rocky territories; highly aggressive toward other mbuna; multiple species described from different localities', notes:'among the largest of the mbuna; the genus name literally means "rock tilapia"' },
  'Copadichromis':  { fam:'Cichlidae', type:'utaka cichlid', habitat:'open water and sand-rock interfaces of Lake Malawi, 5â€“40 m depth', feeding:'pelagic zooplanktivore; forms large schools in open water, sweeping zooplankton with fine gill rakers', behavior:'forms enormous shoals in the open lake; males descend to the bottom during breeding to build sand bower structures to attract females; females mouthbrood', notes:'one of the most abundant fish in the lake by biomass; the "utaka" group is commercially important in Malawi fisheries; dozens of species, many endemic to single bays' },
  'Aulonocara':     { fam:'Cichlidae', type:'peacock cichlid', habitat:'sand-rock interface of Lake Malawi, often 10â€“30 m', feeding:'unique sensory hunter; motionless above sandy substrate, detecting invertebrates beneath the sand using an expanded lateral-line canal system, then diving head-first to extract buried prey', behavior:'males display dazzling iridescent coloration; relatively peaceful for African cichlids; males defend moderate sand territories near rocks; females mouthbrood', notes:'sometimes called "peacock cichlids" for the male\'s brilliant colors; the expanded lateral line pore system on the lower jaw is a key identifying feature and hunting adaptation unique to this genus' },
  'Placidochromis': { fam:'Cichlidae', type:'sand cichlid', habitat:'sandy substrate bordering rocky reefs in Lake Malawi, 5â€“25 m', feeding:'sifts sand for invertebrates; also picks small items from sand surface', behavior:'peaceful; often follows larger sand-disturbing fish to catch exposed invertebrates â€” a commensal behavior recorded in several Placidochromis species', notes:'some species follow Nile tilapia or other large sand-sifters; this "follower" behavior is well-documented and was described in early field studies of the lake\'s ecology' },
  'Nimbochromis':   { fam:'Cichlidae', type:'piscivorous haplochromine', habitat:'sand and transition zones of Lake Malawi, shallow to 15 m', feeding:'piscivore; N. livingstonii uses a remarkable lie-and-lure strategy â€” lying motionless on its side, mimicking a dead or dying fish to attract curious small cichlids, then ambushing them', behavior:'one of the most behaviorally fascinating cichlids; the thanatosis (death-feigning) hunting strategy of N. livingstonii is one of the few confirmed examples of aggressive mimicry in freshwater fish', notes:'N. venustus and N. polystigma are also important piscivores; the genus name roughly translates to "cloud cichlid," referring to the camouflage pattern' },
  'Dimidiochromis': { fam:'Cichlidae', type:'piscivorous haplochromine', habitat:'shallow Vallisneria beds and open sandy areas, Lake Malawi', feeding:'ambush piscivore; lies hidden among aquatic plants and surges forward to engulf prey', behavior:'extremely elongate body; males show striking metallic-blue coloration; one of the more specialized plant-associated predators in the lake', notes:'D. compressiceps has a strongly compressed body and forward-facing eyes that suggest an upward-hunting strategy targeting fish silhouetted against the surface' },
  'Champsochromis': { fam:'Cichlidae', type:'open-water predator', habitat:'open water and littoral zones of Lake Malawi', feeding:'active piscivore; chases prey in open water using excellent vision and speed', behavior:'one of the largest and most predatory haplochromines in Malawi', notes:'called the "Malawi trout" by anglers; the genus name reflects a crocodile-like jaw profile' },
  'Buccochromis':   { fam:'Cichlidae', type:'piscivorous haplochromine', habitat:'open water and rocky reefs of Lake Malawi', feeding:'piscivore; engulfs prey whole using the very large mouth the genus name references', behavior:'solitary or loosely paired; adults are among the largest haplochromines in the lake at 40+ cm', notes:'buccochromis translates to "big-mouthed cichlid"; the name is visually obvious in life' },
  'Protomelas':     { fam:'Cichlidae', type:'benthic haplochromine', habitat:'sand-rock interface and rocky habitat, Lake Malawi, typically 10â€“30 m', feeding:'picks invertebrates and algae material from rock and sand; diet varies significantly among species', behavior:'diverse genus; males typically display bright iridescent coloration; relatively peaceful compared to mbuna', notes:'one of the most species-rich haplochromine genera in Malawi; includes forms that were previously unstable between multiple genera' },
  'Lethrinops':     { fam:'Cichlidae', type:'sand cichlid', habitat:'sandy bottom of Lake Malawi', feeding:'excavates the substrate to find invertebrates; sucks invertebrates from below the surface', behavior:'benthic; males build crater-shaped spawning pits in sand; females mouthbrood', notes:'the oral dentition is adapted for picking and crushing invertebrates in loose substrate; a classic Malawi sand cichlid' },
  'Sciaenochromis': { fam:'Cichlidae', type:'piscivorous haplochromine', habitat:'rocky reefs of Lake Malawi, especially in areas with mouthbrooding mbuna', feeding:'specialist predator on mouthbrooding female cichlids; rams females in the jaw to force them to drop their brood, then swallows the eggs or fry', behavior:'one of the most disturbing predatory strategies in the lake; the electric-blue male (Sciaenochromis fryeri) is among the most widely kept African cichlids in the hobby', notes:'the "electric blue ahli" in the aquarium trade is S. fryeri; its wild hunting of mbuna broods is well-documented in the scientific literature' },

  // â”€â”€ Lake Tanganyika cichlids â”€â”€
  'Tropheus':       { fam:'Cichlidae', type:'rock-dwelling cichlid', habitat:'the surge-battered upper rocky shoreline of Lake Tanganyika, 0.5â€“5 m depth', feeding:'strict grazer of epilithic algae (aufwuchs) on near-vertical rock faces; the digestive system is specialized for plant matter and cannot tolerate high-protein foods in captivity', behavior:'one of the most territorial and socially complex cichlids on Earth; lives in colonies of 50â€“100+ where dominant males each control a small rock patch; rival males fight viciously and non-stop; females are accepted only briefly for mating', notes:'the extraordinary diversity of Tropheus color morphs â€” over 50 named forms of the single species T. moorii alone â€” is driven by extreme geographic isolation across different rocky shoreline sections; populations separated by a sand barrier a few hundred meters wide rapidly diverge in color and refuse to interbreed' },
  'Altolamprologus':{ fam:'Cichlidae', type:'rock-crevice predator', habitat:'rocky areas of Lake Tanganyika, from shallow surge zones to 50+ m', feeding:'ambush predator on invertebrates and small fish; the laterally-compressed body allows entry into rock crevices inaccessible to other predators', behavior:'one of the most architecturally extreme cichlid bodies â€” compressed like a thick coin; males are 3â€“4Ã -  larger than females; biparental spawning in rock crevices or empty snail shells', notes:'the compression of the body has long puzzled biologists; the leading hypothesis is that it allows the fish to follow prey into impossibly tight spaces that predators cannot enter; males guard territory while females guard the brood inside a crevice' },
  'Cyphotilapia':   { fam:'Cichlidae', type:'deepwater predator', habitat:'open water and rocky drop-offs of Lake Tanganyika, 10â€“50 m, primarily 20â€“35 m depth', feeding:'predator; hunts principally at night when it rises from deeper water; primary prey is adult mouthbrooding cichlids (principally Cyprichromis), which it herds to the surface before consuming', behavior:'uniquely structured as a nuchal hump on mature males, giving the "frontosa" its distinctive silhouette; slow-moving and majestic; forms loose dominance hierarchies', notes:'one of the most iconic cichlids in the world; the nuchal hump is a secondary sexual characteristic that grows with age; the midnight hunting behavior rising from depth was confirmed by underwater observation; can live 25+ years in captivity' },
  'Cyprichromis':   { fam:'Cichlidae', type:'pelagic schooling cichlid', habitat:'open water of Lake Tanganyika, 5â€“25 m, always away from substrate', feeding:'zooplanktivore; feeds on copepods and other zooplankton while forming enormous open-water schools', behavior:'one of the few completely pelagic cichlids; forms schools of hundreds or thousands over rocky drop-offs; spawning is astonishing â€” the female releases eggs in free water and the male fertilizes them before she catches them in her mouth', notes:'the open-water spawning â€” where eggs fall freely and must be caught mid-column â€” is one of the most spectacular breeding behaviors in freshwater fish; Cyphotilapia frontosa is known to be a primary predator on these schools' },
  'Xenotilapia':    { fam:'Cichlidae', type:'sand cichlid', habitat:'sandy substrate of Lake Tanganyika, often in deeper water', feeding:'sifts sand for invertebrates, straining it through fine gill rakers', behavior:'biparental mouthbrooder; both parents share egg-carrying duty, passing the brood between them; remarkable parental care system unique among African cichlids', notes:'the biparental mouthbrooding in Xenotilapia â€” where a clutch is passed back and forth between mother and father â€” is one of the most complex parental behaviors known in any fish; it is thought to reduce the cost per individual parent' },
  'Julidochromis':  { fam:'Cichlidae', type:'rock-dwelling cichlid', habitat:'rocky shoreline of Lake Tanganyika, from 1 m to 50+ m', feeding:'picks small invertebrates from rock surface and biofilm', behavior:'forms strict and long-lasting monogamous pair bonds; both parents cooperate in brood defense and spawn repeatedly in rock crevices; one of few cichlids where the sexes look identical outside of subtle fin differences', notes:'the pair bond in Julidochromis can last years; they are popular in aquaria for this reason; several species hybridize at contact zones in the wild, producing a natural hybrid zone that helps scientists study speciation' },
  'Neolamprologus': { fam:'Cichlidae', type:'substrate-spawning lamprologine', habitat:'rocky areas and empty gastropod shell beds of Lake Tanganyika, from 3â€“40 m', feeding:'varies by species; from aufwuchs and invertebrates to small fish', behavior:'a hugely diverse genus containing shell-dwelling species (laying eggs inside Neothauma snail shells), rock crevice spawners, and open substrate breeders; cooperative breeding with helper offspring documented in some species', notes:'N. pulcher (previously N. brichardi) is famous in behavioral biology for having "helpers at the nest" â€” previous broods that stay to protect subsequent clutches, one of very few fish known to do this; the genus contains 50+ species' },
  'Lamprologus':    { fam:'Cichlidae', type:'substrate-spawning cichlid', habitat:'rocky and sandy substrate, Lake Tanganyika', feeding:'invertebrates and small fish', behavior:'many species are shell dwellers, breeding exclusively inside empty snail shells; males often guard multiple shell-dwelling females in a loose harem', notes:'shell-dwelling in Lake Tanganyika cichlids is an innovation that arose multiple times independently; the empty shells of the endemic Neothauma snail are the primary dwelling sites' },
  'Eretmodus':      { fam:'Cichlidae', type:'goby-cichlid', habitat:'surge zone of Lake Tanganyika, 0â€“3 m, in the most wave-battered shoreline', feeding:'grazes epilithic algae in the extreme shallow surge zone', behavior:'strongly pair-bonded; biparental mouthbrooder; the pair occupies a fixed territory and spawns repeatedly; both sexes look identical', notes:'one of three "goby cichlids" of Tanganyika (with Tanganicodus and Spathodus) that convergently evolved a goby-like body plan for surge-zone life; molecular analysis reveals they are genuine cichlids, not gobies, that adapted independently to the wave zone' },
  'Spathodus':      { fam:'Cichlidae', type:'goby-cichlid', habitat:'surge zone rocks, Lake Tanganyika, 0â€“3 m', feeding:'grazes algae in the extreme shoreline surge zone', behavior:'solitary; unlike the monogamous Eretmodus, Spathodus erythrodon is notably non-social; biparental mouthbrooder', notes:'one of the three goby-cichlids of Tanganyika; differs from Eretmodus in being solitary rather than pair-bonded, despite sharing a nearly identical ecological niche and body plan' },
  'Lobochilotes':   { fam:'Cichlidae', type:'herbivorous cichlid', habitat:'rocky shoreline, Lake Tanganyika', feeding:'grazes algae using extremely fleshy, expandable lips that give the genus its name ("lobe-lipped cichlid")', behavior:'solitary; one of the largest rocky-shore cichlids in Tanganyika at 30+ cm', notes:'the remarkable lip structure is an adaptation for grazing on near-vertical rock faces; the flexible fleshy lobes allow feeding at angles that would damage harder mouth structures' },
  'Perissodus':     { fam:'Cichlidae', type:'scale-eating cichlid', habitat:'rocky areas, Lake Tanganyika', feeding:'lepidophage; sneaks up to other fish and bites off scales â€” some individuals are left-jawed specialists, others right-jawed, creating a frequency-dependent evolutionary arms race with prey fish who become more alert to attacks from the prevalent side', behavior:'one of the most famous examples of frequency-dependent selection in nature; the jaw asymmetry of this fish â€” with some individuals skewed left and some right â€” is a textbook example of evolutionary biology', notes:'the jaw asymmetry and frequency-dependent selection in Perissodus microlepis has been described in major evolutionary biology textbooks since the 1990s; it is one of the clearest natural examples of a stable genetic polymorphism maintained by predator-prey co-evolution' },

  // â”€â”€ Lake Victoria cichlids â”€â”€
  'Haplochromis':   { fam:'Cichlidae', type:'haplochromine cichlid', habitat:'various habitats in Lake Victoria, Lake Kyoga, and connecting waters', feeding:'highly variable by species; includes algae scrapers, invertebrate pickers, piscivores, insectivores, zooplankton feeders, and scale eaters', behavior:'formed the single most rapid vertebrate radiation in evolutionary history â€” over 500 species evolved in Lake Victoria in just 15,000 years from a single ancestor; most are oral mouthbrooders', notes:'the Nile perch introduction to Lake Victoria in the 1950s caused the extinction or near-extinction of over 200 Haplochromis species â€” the single largest vertebrate mass extinction in recorded history; surviving species are now critical conservation subjects' },
  'Pundamilia':     { fam:'Cichlidae', type:'rock cichlid', habitat:'rocky inshore areas of Lake Victoria', feeding:'invertebrates and algae', behavior:'famous in evolutionary biology for parallel speciation driven by light environment â€” in murky water, blue and red males look similar and hybridize; in clear water they are visually distinct and maintain species boundaries', notes:'Pundamilia nyererei and P. pundamilia are a key model system for understanding how vision and light environment drive speciation; published in Nature and Science; the cichlid radiation of Victoria is considered the fastest known vertebrate speciation event' },

  // â”€â”€ South/Central American cichlids â”€â”€
  'Apistogramma':   { fam:'Cichlidae', type:'dwarf cichlid', habitat:'shallow, slow-moving, leaf-littered blackwater streams of Amazonia and Orinoco basin, typically under 50 cm deep', feeding:'feeds on small invertebrates, crustaceans, and insect larvae picked from leaf litter and the substrate', behavior:'extreme sexual dimorphism; females are small and yellow, males 2â€“3Ã -  larger with elaborate finnage and dramatic color; females provide all brood care in a defended leaf or crevice while males guard the territory perimeter; temperature-dependent sex determination in some species', notes:'with 400+ described subspecies and morphs, Apistogramma may be the most taxonomically complex freshwater fish genus on Earth; many species are so recent that formal descriptions lag behind collector discovery by a decade or more; blackwater water chemistry (very soft, acidic, low conductivity) is critical for spawning in most species' },
  'Geophagus':      { fam:'Cichlidae', type:'earth-eating cichlid', habitat:'large South American rivers and lakes, benthic zones, primarily sandy or fine-gravel substrate', feeding:'picks up mouthfuls of substrate, sifts invertebrates and organic material through gill rakers, and expels the sand; also takes invertebrates and plant material directly', behavior:'mouthbrooder; the substrate-sifting feeding creates visible cone-shaped depressions in the riverbed; forms loose groups; relatively peaceful for a cichlid', notes:'the name Geophagus means "earth-eater" â€” their constant substrate sifting has significant ecological effects, turning over and oxygenating sediments across vast areas of South American rivers' },
  'Satanoperca':    { fam:'Cichlidae', type:'earth-eating cichlid', habitat:'deep sandy benthic zones of Amazonian and Orinoco rivers', feeding:'substrate-sifter like Geophagus; specializes in deeper substrate excavation than most geophagines', behavior:'delayed mouthbrooder; parents allow fry to move freely on the substrate but both parents gather them into their mouths at any threat', notes:'the genus name ("Satanoperca") translates to "devil perch" â€” ironic for a fish that is docile and functions more as an ecosystem engineer than a predator; the dramatic excavation leaves distinctive pit fields visible on river bottoms' },
  'Crenicichla':    { fam:'Cichlidae', type:'pike cichlid', habitat:'rivers and streams throughout South America, typically associated with rocks, wood, and leaf litter at stream margins', feeding:'active ambush predator; the elongate body and large mouth allow rapid lunging from cover to engulf fish, crustaceans, and large invertebrates', behavior:'solitary and aggressive; one of the most diverse freshwater predatory cichlid genera; males typically develop iridescent red and blue spots; pair bond during breeding', notes:'pike cichlids have undergone extraordinary diversification; over 100 species are described, many from single river drainages; convergent evolution of the elongate pike-like body has happened multiple times across cichlid lineages on different continents' },
  'Mikrogeophagus': { fam:'Cichlidae', type:'dwarf earth-eating cichlid', habitat:'slow, shallow, acidic streams and pools of Amazonia (M. ramirezi in Venezuela/Colombia, M. altispinosus in Bolivia/Brazil)', feeding:'picks invertebrates carefully from substrate and leaf litter', behavior:'the "ram cichlid" (M. ramirezi) is among the most popular aquarium fish globally; pair bond strongly; biparental brood care; mating displays include vibratory shimmy and lateral displays', notes:'M. ramirezi has been domesticated into dozens of color morphs in the aquarium trade (electric blue, golden, balloon); wild populations in Venezuela are increasingly threatened by collection pressure and habitat degradation' },
  'Pterophyllum':   { fam:'Cichlidae', type:'angelfish', habitat:'slow-moving rivers and flooded forest of Amazonia, typically in areas with dense aquatic vegetation or submerged wood', feeding:'ambush predator; the disc-shaped, laterally-compressed body allows the angelfish to disguise itself among vertical reeds and roots, then lunge at small fish and invertebrates', behavior:'forms pair bonds; biparental spawning on vertical surfaces (broad leaves, reed stems); fry remain attached to the surface by a sticky thread for the first few days', notes:'the extraordinary disc shape and high-set dorsal fin make the angelfish one of the most recognizable freshwater fish in the world; wild forms are far more variable in color and markings than the domesticated strains that dominate the aquarium trade' },
  'Symphysodon':    { fam:'Cichlidae', type:'discus cichlid', habitat:'flooded vÃ¡rzea forest, blackwater lakes, and slow backwaters of the central Amazon; requires complex root and leaf structure', feeding:'picks invertebrates, algae, and organic detritus from wood and leaf surfaces; young fry feed for several weeks on specialized mucus secreted from the parents\' skin â€” unique among cichlids', notes:'skin-mucus feeding by discus fry is one of the most unusual parental behaviors in fish; both parents produce the mucus and the fry actively rasp it from their bodies for the first 3 weeks of life before transitioning to independent feeding; the color morphs of wild and captive discus are extraordinary, ranging from the turquoise Amazon form to the brilliant heckel discus' },
  'Cichla':         { fam:'Cichlidae', type:'peacock bass', habitat:'large rivers and reservoirs of South America; requires open water and structure', feeding:'apex piscivore; the most feared predator in Amazonian rivers; hunts actively by day in open water and ambushes near structure at dawn and dusk', notes:'introduced populations of Cichla ocellaris to lakes and reservoirs outside its native range have caused catastrophic biodiversity collapses; the Lake GatÃºn introduction in Panama wiped out most native fish fauna; Cichla is now one of the best-documented examples of introduced predator impacts' },
  'Rocio':          { fam:'Cichlidae', type:'Central American cichlid', habitat:'Mexican and Central American rivers, preferring slow, turbid water over muddy substrate', feeding:'omnivore; picks invertebrates, plant material, algae, and small fish from substrate', behavior:'biparental substrate spawner; defends territory aggressively; R. octofasciata (jack dempsey) named after the boxer for its ferocity', notes:'the jack dempsey cichlid was one of the earliest "aggressive cichlid" species popularized in the aquarium hobby; kept since the early 20th century; named after the heavyweight boxing champion of the 1920s' },
  'Thorichthys':    { fam:'Cichlidae', type:'Central American cichlid', habitat:'rivers and streams of Mexico and Central America, often in limestone-rich water over sandy or silty substrate', feeding:'sifts substrate for invertebrates and plant material; T. meeki (firemouth) is named for the vivid red throat used in threat displays', behavior:'threat display in T. meeki involves flaring the gill cover to expose the red throat membrane, making the fish appear larger; most conflicts are resolved by display alone without contact', notes:'the firemouth cichlid has been kept in aquaria since the 1920s; the threat display gill flare has been extensively studied as a model for ritualized conflict resolution in vertebrates' },
  'Herichthys':     { fam:'Cichlidae', type:'Central American cichlid', habitat:'rivers, springs, and caves of Mexico and Texas (reach into southern United States)', feeding:'bottom feeder; uses specially adapted jaws to crack mollusk shells and extract invertebrates from dense substrate', notes:'H. cyanoguttatus is the only cichlid native to the United States; the "Texas cichlid" occurs naturally in the Rio Grande and has established invasive populations further north; some Herichthys populations are spring-endemic and relict species with very restricted ranges' },

  // â”€â”€ Tanganyika non-cichlid â”€â”€
  'Mastacembelus':  { fam:'Mastacembelidae', type:'spiny eel', habitat:'rocky substrate and crevices of Lake Tanganyika; also rivers of Africa and Asia', feeding:'invertebrates and small fish found in rock crevices and substrate', behavior:'nocturnal; hides in tight crevices during the day; uses the elongate rostrum to probe substrate', notes:'not a true eel but a spiny eel; the Tanganyikan endemic Mastacembelus species represent a fascinating diversity of river-to-lake colonization' },

  // â”€â”€ Marine: Surgeonfish (Acanthuridae) â”€â”€
  'Acanthurus':     { fam:'Acanthuridae', type:'surgeonfish', habitat:'coral reefs and hard substrate to 30+ m across tropical Indo-Pacific and Atlantic', feeding:'algae grazer; uses a small mouth with scraping or brush-like teeth to remove algae, detritus, and diatoms from hard surfaces; performs an ecosystem service keeping reefs from being overgrown', behavior:'forms schools for foraging, which overwhelms the territorial defenses of damselfish and other algae farmers; the caudal "scalpel" â€” a retractable razor-sharp spine at the base of the tail â€” is used defensively when handled or threatened', notes:'surgeonfish play a critical role in reef ecology; their grazing prevents macroalgae from smothering coral colonies; overfishing of surgeonfish in some regions has measurably increased algae cover on reefs' },
  'Paracanthurus':  { fam:'Acanthuridae', type:'palette surgeonfish', habitat:'coral-rich areas of the tropical Indo-Pacific, 2â€“40 m', feeding:'omnivore; feeds on zooplankton in the water column (unusual for surgeonfish) as well as algae', behavior:'hides in Acropora coral branches when threatened; juveniles particularly associated with branching corals; the species was made globally famous as "Dory" in Finding Nemo/Finding Dory', notes:'P. hepatus is the only member of its genus; it can tolerate a wider range of water conditions than most surgeonfish, making it one of the most common surgeonfish in the marine aquarium trade; IUCN lists it as Least Concern but collection pressure is significant' },
  'Zebrasoma':      { fam:'Acanthuridae', type:'tang', habitat:'reef flats, lagoons, and outer reef of tropical Indo-Pacific and Red Sea', feeding:'grazes filamentous algae using a disc-shaped body that lets it enter tight crevices inaccessible to other fish; the long snout extends the reach' },
  'Naso':           { fam:'Acanthuridae', type:'unicornfish', habitat:'outer reef slopes and drop-offs, tropical Indo-Pacific, 5â€“50 m', feeding:'grazes on coarse macro-algae such as Sargassum and other brown algae less palatable to other fish; many species have a rostral horn whose function is not fully understood', behavior:'some species are pelagic migrators; adults of some Naso species migrate in schools over open ocean to spawning aggregations', notes:'the rostral horn common to many Naso species grew to considerable length and is one of the more visually dramatic features of any reef fish; its function in display or hydrodynamics is still debated' },

  // â”€â”€ Marine: Angelfish (Pomacanthidae) â”€â”€
  'Pomacanthus':    { fam:'Pomacanthidae', type:'large angelfish', habitat:'coral-rich areas of tropical oceans to 30 m', feeding:'spongivore and omnivore; adults feed primarily on sponges, tunicates, and other sessile invertebrates that most fish cannot digest; juveniles have dramatically different markings from adults', behavior:'juveniles act as cleaners at cleaning stations, picking parasites from other fish; the adult coloration is entirely different from juvenile, which was historically described as separate species before their connection was understood', notes:'the juvenile-to-adult color transformation in large Pomacanthus is extraordinary; the juvenile P. semicirculatus is white with concentric blue-white arcs, while the adult is deep blue-green; the transformation was not understood until naturalists raised individuals in captivity' },
  'Holacanthus':    { fam:'Pomacanthidae', type:'large angelfish', habitat:'coral reefs of the Atlantic and Eastern Pacific', feeding:'spongivore; feeds primarily on sponges and tunicates; also takes sea squirts and zoanthids', notes:'H. ciliaris (queen angelfish) and H. tricolor (rock beauty) are among the most recognizable reef fish of the Caribbean; both are heavily targeted by the ornamental fish trade; the queen angelfish is one of very few fish species that has a genuine "queen" morph with a distinctive crown-like spot on the head' },
  'Centropyge':     { fam:'Pomacanthidae', type:'dwarf angelfish', habitat:'coral reef rubble zones and crevice-rich areas, tropical Indo-Pacific and Atlantic, 1â€“70 m', feeding:'grazes algae and detritus from rock surfaces; the small size allows access to microhabitats inaccessible to larger angelfish', behavior:'protogynous hermaphrodite; all individuals are born female; dominant individuals transition to male when the male of a group is lost', notes:'protogynous hermaphroditism is common in this family; the sex change is triggered by social factors and involves significant hormonal and physical transformation; dwarf angelfish are among the most commonly kept marine aquarium fish due to their small size' },
  'Genicanthus':    { fam:'Pomacanthidae', type:'swallowtail angelfish', habitat:'outer reef slopes and drop-offs, 10â€“60 m', feeding:'planktivore; the only angelfish genus that feeds primarily in the water column on zooplankton, not on sessile invertebrates', behavior:'sexually dichromatic; males and females look entirely different; forms harems with one dominant male; males perform spiraling water-column spawning rises', notes:'the swallowtail angelfish\'s plankton-feeding lifestyle is unique among the Pomacanthidae; their elongated tail lobes and schooling behavior in open water above reef slopes is strikingly different from other angelfish' },

  // â”€â”€ Marine: Butterflyfish (Chaetodontidae) â”€â”€
  'Chaetodon':      { fam:'Chaetodontidae', type:'butterflyfish', habitat:'coral reefs of tropical oceans, typically 1â€“30 m', feeding:'obligate corallivore in many species â€” feeding exclusively on coral polyps and tissue; others eat invertebrates, zoanthids, or tube worm tentacles; the long snout allows extraction from tight coral architecture', behavior:'forms monogamous pair bonds that can persist for years; pairs occupy and defend a defined reef territory together; the bold eyespot marking near the tail is thought to misdirect predators', notes:'butterflyfish are among the best biological indicators of coral reef health â€” because so many species are coral specialists, their disappearance signals coral decline; reef monitoring programs use Chaetodon counts to track reef condition' },
  'Heniochus':      { fam:'Chaetodontidae', type:'bannerfish', habitat:'coral reefs and lagoons, Indo-Pacific and Red Sea', feeding:'invertebrates, zooplankton, and algae; some species act as cleaners of parasites on larger fish', notes:'the extended white anal and dorsal fin filament of Heniochus gives the "bannerfish" appearance; some species closely mimic the moorish idol (Zanclus cornutus) in shape and coloration, which may offer protection' },

  // â”€â”€ Marine: Wrasses (Labridae) â”€â”€
  'Cirrhilabrus':   { fam:'Labridae', type:'fairy wrasse', habitat:'reef slopes and rubble zones of the Indo-Pacific, typically 5â€“60 m', feeding:'picks zooplankton and small invertebrates from the water column just above the reef', behavior:'protogynous hermaphrodite; males display spectacular iridescent colors and perform arial spinning courtship jumps during spawning; harems of multiple females attend the dominant male', notes:'fairy wrasses are among the most species-rich marine fish genera; many species were described only in the past 30 years from deepwater reef surveys; males in super-coloration display are among the most vivid animals on any reef' },
  'Cheilinus':      { fam:'Labridae', type:'wrasse', habitat:'coral reef structures, Indo-Pacific', feeding:'attacks hard-shelled invertebrates including sea urchins, crabs, and hermit crabs; the thick pharyngeal teeth crush hard exoskeletons', notes:'C. undulatus (Napoleon/humphead wrasse) is one of the largest reef fish at 2 m and 180 kg; listed as Endangered; heavily targeted by the live reef fish food trade in Asia; protected in most of its range but enforcement is poor' },
  'Halichoeres':    { fam:'Labridae', type:'wrasse', habitat:'shallow reef, seagrass, and rubble zones of tropical and subtropical oceans', feeding:'turns over substrate and rubble to expose invertebrates; picks off small crustaceans and worms', behavior:'protogynous; juveniles often act as parasite pickers at cleaning stations before developing adult color patterns', notes:'one of the most species-rich and morphologically variable wrasse genera; some species are important cleaning fish at dedicated cleaning stations on reef' },
  'Thalassoma':     { fam:'Labridae', type:'wrasse', habitat:'shallow exposed reef crests and surge zones of tropical oceans', feeding:'active swimmer; picks invertebrates and small fish from reef surface; some species feed on echinoderm tube feet', behavior:'fast, strong swimmers adapted to wave-surge habitat; terminal-phase males are dazzlingly colored; initial phase fish (females + young males) are cryptically striped', notes:'T. bifasciatum (bluehead wrasse) has been a major model species in studies of sex change endocrinology; its hormonal sex reversal has been studied in detail in Caribbean marine biology programs' },
  'Bodianus':       { fam:'Labridae', type:'hogfish', habitat:'coral and rocky reefs, 5â€“40 m, tropical and subtropical', feeding:'crushes invertebrates including sea urchins, crabs, and mollusks with powerful pharyngeal jaws', behavior:'some species are obligate cleaners; others actively hunt invertebrates; juveniles of many species act as cleaners before transitioning to predatory adult habits', notes:'hogfish are commercially important in the Caribbean; B. rufus (Spanish hogfish) is highly prized as table fish and also serves as an important cleaner in Atlantic reefs' },
  'Lachnolaimus':   { fam:'Labridae', type:'hogfish', habitat:'coral reefs and rocky outcrops, Gulf of Mexico and Caribbean, 1â€“40 m', feeding:'specialist mollusk-crusher; uses the powerful pharyngeal jaw to crush clams, oysters, and other hard-shelled prey; the snout is adapted for rooting through rubble', notes:'L. maximus (hogfish) is one of the prized food fish of the Caribbean; the protogynous sex change is commercially important because fishermen tend to preferentially removed the large terminal males, skewing sex ratios in fished populations' },

  // â”€â”€ Marine: Damselfish / Chromis (Pomacentridae) â”€â”€
  'Chromis':        { fam:'Pomacentridae', type:'chromis damselfish', habitat:'open water just above coral reefs of tropical oceans, 1â€“30 m', feeding:'planktivore; feeds in large aggregations in the water column on zooplankton, retreating to coral branches when threatened', behavior:'forms large social aggregations; substrate spawner; males guard demersal egg patches and fan them with fins to oxygenate the clutch', notes:'Chromis viridis (green chromis / blue-green chromis) is one of the most abundant fish on Indo-Pacific reefs and one of the most common aquarium fish globally; forms spectacular shoals of thousands above branching Acropora corals' },
  'Chrysiptera':    { fam:'Pomacentridae', type:'demoiselle damselfish', habitat:'shallow reef flats and lagoons of the Indo-Pacific, 0â€“10 m', feeding:'picks algae, zooplankton, and small benthic invertebrates', behavior:'aggressively territorial; tiny fish (5â€“8 cm) that will attack fish many times their size; farming behavior documented where some species tend and defend an algae garden', notes:'the territorial aggression of damselfish per unit body size is among the highest in reef fish; their constant harassment of much larger passersby is one of the most visible behaviors on any Indo-Pacific reef flat' },
  'Amphiprion':     { fam:'Pomacentridae', type:'clownfish / anemonefish', habitat:'within the tentacles of host sea anemones on Indo-Pacific coral reefs, 1â€“15 m', feeding:'omnivore; feeds on zooplankton, algae, and leftover food scraps from the anemone host; the fish-anemone relationship is mutualistic â€” the clownfish drives away anemone predators and provides nutrients via feces', behavior:'protandrous hermaphrodite â€” all clownfish are born male; when the dominant female of a group dies, the largest male transitions to female; juveniles settle into anemones and establish a dominance hierarchy', notes:'A. ocellaris and A. percula became globally famous after Finding Nemo (2003); ironically the film dramatically increased collection pressure on wild populations; the mutualistic relationship with anemones is one of the most studied mutualisms in marine biology; clownfish tolerance to anemone venom is achieved via a mucus coating that suppresses anemone nematocyst firing' },
  'Premnas':        { fam:'Pomacentridae', type:'maroon clownfish', habitat:'Bubbletip anemone (Entacmaea quadricolor) in the tropical Indo-Pacific', feeding:'omnivore; similar diet to Amphiprion but exclusively associates with Entacmaea anemones', behavior:'the most aggressive of all clownfish; females can reach 17 cm; males are dwarfed at 5 cm; the single-anemone monogamy is enforced violently', notes:'P. biaculeatus (maroon clownfish) has a distinct cheek spine absent in Amphiprion; it is the largest and most belligerent clownfish and one of the few that will actively bite divers who approach its anemone' },
  'Dascyllus':      { fam:'Pomacentridae', type:'humbug damselfish', habitat:'shelters within coral heads and branching corals of the Indo-Pacific and Red Sea, 1â€“20 m', feeding:'picks zooplankton from the water column near the shelter coral', behavior:'highly dependent on coral heads for refuge; rarely strays more than 1 m from the coral; the three-spot dascyllus (D. trimaculatus) uses sea anemones as a shelter host, similar to clownfish', notes:'the dependence on specific coral species for shelter makes Dascyllus particularly vulnerable to coral bleaching events; population crashes following bleaching events in the Red Sea have been recorded and studied' },

  // â”€â”€ Marine: Sea bass / Grouper (Serranidae) â”€â”€
  'Cephalopholis':  { fam:'Serranidae', type:'grouper', habitat:'coral reefs and rocky areas, tropical Indo-Pacific and Atlantic, 1â€“40 m', feeding:'ambush predator; conceals in crevices and engulfs prey fish with a rapid expansion lunge', behavior:'protogynous hermaphrodite; all individuals start as female, transitioning to male when large enough to win spawning aggregations', notes:'groupers are keystone reef predators; their removal through overfishing causes measurable trophic cascades; most Cephalopholis species are commercially fished and several are in significant decline' },
  'Epinephelus':    { fam:'Serranidae', type:'grouper', habitat:'coral and rocky reefs worldwide, 1â€“300+ m depending on species', feeding:'apex ambush predator; the enormous mouth creates suction to engulf prey fish whole; some species consume octopus and crustaceans', behavior:'forms spawning aggregations of thousands at predictable times and locations; these aggregations are heavily targeted by fishermen; some species display synchronized broadcasting of eggs and sperm during mass spawning events', notes:'spawning aggregations are critically vulnerable; at some historic sites in the Caribbean, Nassau grouper (E. striatus) went from thousands to zero in a decade of targeted aggregation fishing; the species is now Endangered' },

  // â”€â”€ Marine: Seahorses (Syngnathidae) â”€â”€
  'Hippocampus':    { fam:'Syngnathidae', type:'seahorse', habitat:'seagrass beds, coral, algae, and mangroves globally in tropical and warm-temperate oceans', feeding:'ambush micro-predator; lacks a stomach; must eat almost continuously; uses the tubular snout as a pipette, generating a tiny hydraulic snap to slurp up copepods and small crustaceans', behavior:'the only genus of vertebrates in which the male carries the young; females deposit eggs into the male\'s brood pouch where they are fertilized and incubated; the male gives "birth" after 10â€“45 days; pairs are monogamous and greet each other each morning with synchronized color display', notes:'seahorse populations have declined severely globally; trade in dried seahorses for traditional medicine was consuming 30+ million individuals per year before CITES regulation; further threatened by seagrass and coral loss; the male pregnancy and male-female morning greeting ceremonies make seahorses one of the most biologically fascinating fish on Earth' },

  // â”€â”€ Marine: Eels (Muraenidae) â”€â”€
  'Gymnothorax':    { fam:'Muraenidae', type:'moray eel', habitat:'crevices and caves on coral and rocky reefs worldwide, 1â€“50 m', feeding:'ambush predator; the famous forward jaw is actually accompanied by a second set of pharyngeal jaws (like Alien) that spring forward to pull prey into the throat after the oral jaws grab it â€” unique among vertebrates', behavior:'rests in crevices with mouth open â€” not threatening behavior but necessary for breathing without a gill cover; forms remarkable cooperative hunting partnerships with roving groupers (documented formally in 2006)', notes:'the double-jaw mechanism (pharyngeal jaw independent strike) was published in Nature in 2007 as the first vertebrate discovered to use pharyngeal jaws as an independent predatory tool; the cooperative hunting with giant grouper â€” where each species benefits from the other\'s hunting style â€” was one of the most surprising behavioral discoveries in marine biology of the 21st century' },
  'Rhinomuraena':   { fam:'Muraenidae', type:'ribbon eel', habitat:'sand and rubble zones of Indo-Pacific reefs, 1â€“55 m', feeding:'fish predator; lies in a crevice with the elaborate nasal leaf-lures extended to attract prey into lunging distance', behavior:'sequential hermaphrodite; all ribbon eels hatch as male (black with yellow dorsal fin); mature males are vivid blue; females are yellow; a single individual goes through all three color phases in one lifetime', notes:'the sequential color change from black â†’ blue â†’ yellow as the animal transitions from juvenile to male to female is one of the most spectacular and well-documented sex-change sequences in any vertebrate; many divers specifically seek out ribbon eels for photography' },

  // â”€â”€ Marine: Parrotfish (Scaridae / Labridae) â”€â”€
  'Scarus':         { fam:'Scaridae', type:'parrotfish', habitat:'coral reefs and seagrass beds of tropical oceans', feeding:'bites coral with fused beak-like teeth to extract endolithic algae growing inside coral skeletons; a significant portion of white tropical beach sand is parrotfish feces â€” finely ground calcium carbonate from digested coral', behavior:'terminal phase males are vivid blue-green; initial phase fish are mottled brown; wraps itself in a mucus cocoon at night thought to mask its scent from eels', notes:'a single large parrotfish can produce hundreds of kilograms of sand per year; the white sand beaches of the Maldives, Caribbean, and Polynesia depend critically on parrotfish; declines in parrotfish populations due to overfishing have measurably reduced sand production and increased coral algae cover on multiple Caribbean reefs' },
  'Chlorurus':      { fam:'Scaridae', type:'parrotfish', habitat:'coral reefs, tropical Indo-Pacific and Red Sea', feeding:'algae excavator from coral substrate; bioerosion specialist', notes:'chlorurus parrotfish are among the highest-biomass fish in their habitats; their reef bioerosion role is critical to maintaining the carbonate balance of reef systems' },

  // â”€â”€ Marine: Triggerfishes (Balistidae) â”€â”€
  'Rhinecanthus':   { fam:'Balistidae', type:'triggerfish', habitat:'sand and rubble flats of Indo-Pacific reefs, 0â€“10 m', feeding:'omnivore; picks invertebrates and carries small rocks to expose prey; uses jets of water to uncover sand-buried animals', behavior:'aggressively defends nests by biting anything that enters a conical territory extending straight upward from the nest; has been known to draw blood from divers and drive sharks away', notes:'the picasso triggerfish (R. aculeatus) is one of the most recognizable reef fish and one of Hawaii\'s state fish (humuhumunukunukuÄpuaÊ»a), named in an ancient Hawaiian chant; the upward-pointing trigger territory is unusual â€” divers swimming above nesting picasso triggers are sometimes charged' },
  'Balistapus':     { fam:'Balistidae', type:'triggerfish', habitat:'coral reefs of the Indo-Pacific, 1â€“30 m', feeding:'powerful biter; the orange-lined triggerfish (B. undulatus) can bite through sea urchin spines and coral; one of the most aggressive reef fish toward divers in the Indo-Pacific', notes:'B. undulatus is considered one of the most problematic fish for divers in Southeast Asia due to its territorial nesting aggression; marine protected areas see higher encounter rates as populations recover' },

  // â”€â”€ Freshwater: Catfish â”€â”€
  'Corydoras':      { fam:'Callichthyidae', type:'armored catfish', habitat:'slow-moving, often oxygen-poor blackwater streams, rivers, and flooded flats of South America', feeding:'benthic scavenger; picks invertebrates, plant debris, and organic particles from substrate using sensitive barbels around the mouth', behavior:'highly social; wild Corydoras move in groups of dozens to hundreds of individuals; surfaces regularly to gulp atmospheric air when oxygen levels are low (intestinal breathing); not a schooling fish but a dense foraging aggregation', notes:'Corydoras are one of the most speciose freshwater fish genera with 150+ valid species; their armor of bony scutes (as opposed to scales) protects them from most predators; the barbels contain chemoreceptors used to detect food under substrate; they are among the most popular aquarium fish globally and have been captive-bred for over 100 years' },
  'Ancistrus':      { fam:'Loricariidae', type:'bristlenose plecostomus', habitat:'fast-moving, oxygenated rivers and streams of South America, typically attached to rocks behind waterfalls and in rapids', feeding:'algae and biofilm scraper; the oral disc acts as a suction cup to hold position in fast current while the teeth rasp algae from rock surfaces', behavior:'males develop elaborate tentacle-like fleshy projections on the snout (the "bristles"); males guard eggs in rock holes and fan them continuously; can breed in near-standing water despite naturally occurring in fast water', notes:'bristlenose catfish males with snout tentacles are unusual â€” the function relating to female mate choice is documented; males with more elaborate bristles attract more females; they have been captive-bred for so long that many aquarium populations are several generations removed from known wild ancestors' },
  'Hypostomus':     { fam:'Loricariidae', type:'plecostomus', habitat:'rivers and lakes of South America, benthic on rocks and wood', feeding:'algae and detritus scraper; also uses the oral disc to rasp soft wood fibers and biofilm', notes:'very species-rich genus with 130+ species; many "common plecostomus" in the aquarium trade are sold under this name but may belong to multiple genera; can reach 50+ cm; the common pleco introduced to Florida waterways has become an invasive problem' },

  // â”€â”€ Freshwater: Bettas / Gouramis (Osphronemidae) â”€â”€
  'Betta':          { fam:'Osphronemidae', type:'fighting fish / labyrinth fish', habitat:'shallow rice paddies, streams, ponds, and drainage ditches of Southeast Asia; tolerates low oxygen, stagnant, and warm water', feeding:'surface insectivore; most Betta species are primarily insect larvae specialists, taking prey from the water surface or picking submerged invertebrates', behavior:'the labyrinth organ allows Betta to breathe surface air directly, enabling survival in oxygen-depleted water; males of most species are intensely aggressive toward other males and build elaborate bubble nests at the surface; females are typically drab while males are spectacularly colored; B. splendens has been selectively bred for 500+ years in Thailand into hundreds of fin and color varieties', notes:'wild Betta splendens look almost nothing like the aquarium form â€” they are short-finned, dull-colored, and small; selective breeding over centuries has produced creatures so different from wild ancestors they cannot function in normal water conditions because their fins are too large to swim effectively; the "plakat" (short-finned) form most closely resembles the wild type' },

  // â”€â”€ Freshwater: Misc â”€â”€
  'Danio':          { fam:'Cyprinidae', type:'danio', habitat:'fast-moving streams and drainage channels of South and Southeast Asia, with clean, well-oxygenated water', feeding:'surface feeder; primarily insects and zooplankton picked from the water surface or caught just below it', behavior:'active schooling fish; zebrafish (D. rerio) is one of the most important vertebrate model organisms in biomedical research â€” its transparent embryo allowed the study of vertebrate development in real time; regenerative capacity (regrowing fins, heart tissue) is actively studied for human medical application', notes:'D. rerio (zebrafish) has been central to over 30,000 published scientific papers and is the most studied fish in biomedical research history; the transparent embryo allows direct observation of organ formation; tools developed for zebrafish genetics have been extended to human disease research' },
  'Carassius':      { fam:'Cyprinidae', type:'goldfish / crucian carp', habitat:'ponds, lakes, and slow rivers of East Asia; remarkably tolerant of cold and oxygen-depleted water', feeding:'omnivore; feeds on algae, invertebrates, plant matter, and detritus', behavior:'goldfish (C. auratus) have been selectively bred in China for over 1,000 years â€” the earliest documented example of ornamental fish breeding by humans; selective breeders developed over 200 color and form varieties; can survive complete ice-over in frozen ponds by entering metabolic suppression', notes:'the goldfish is the first fish species domesticated for purely ornamental purposes; the earliest records of goldfish breeding date to the Tang Dynasty (c. 618â€“907 AD); the varieties produced range from the natural-looking comet goldfish to the bubble-eye, telescope, and ryukin forms that barely resemble a fish at all' },
  'Hyphessobrycon': { fam:'Characidae', type:'tetra', habitat:'blackwater streams and pools of South America, typically soft, acidic, leaf-littered streams', feeding:'omnivore; picks insects, small invertebrates, and plant matter from the water column and surface', behavior:'schooling; schools of tetras in the wild can number in the thousands; schooling provides predator confusion and dilution of individual risk', notes:'the many neon-like tetras in the genus (H. amandae "ember tetra," H. erythrostigma "bleeding heart tetra") are among the most commercially important aquarium fish; many species were described only when collected by aquarium exporters, meaning the aquarium trade has directly contributed to tropical fish taxonomy' },
  'Paracheirodon': { fam:'Characidae', type:'neon tetra', habitat:'blackwater streams of Amazonia and Orinoco', feeding:'omnivore; zooplankton, small invertebrates, and algae', notes:'P. innesi (neon tetra) is the world\'s single most-traded aquarium fish; over 1.5 billion are exported from Southeast Asia farms annually (where most are now captive-bred); wild populations are still collected from Amazonia; the iridescent blue stripe uses structural coloration (crystalline guanine platelets) rather than pigment, which means it changes appearance with viewing angle' },
  'Acipenser':      { fam:'Acipenseridae', type:'sturgeon', habitat:'large rivers, estuaries, and coastal oceans of the Northern Hemisphere', feeding:'benthic feeder; drags four sensitive barbels along the riverbed to locate invertebrates, crustaceans, and small fish to engulf with a protrusible tubular mouth', behavior:'highly migratory; anadromous species migrate hundreds or thousands of miles from ocean to spawning rivers; the longest-lived freshwater fish â€” some individuals exceed 100 years old; late to mature (8â€“25 years)', notes:'sturgeons are among the most endangered fish family on Earth; 23 of 27 species are critically endangered, endangered, or vulnerable; illegal caviar trade is the primary driver; some species have not been documented reproducing in the wild in decades; considered "living fossils" because the genus is 200+ million years old and has changed little since the Cretaceous' },
  'Esox':           { fam:'Esocidae', type:'pike / pickerel / muskellunge', habitat:'weedy lakes, rivers, and backwaters of the Northern Hemisphere', feeding:'ambush apex predator; lies motionless among vegetation and ambushes prey of any size including waterfowl, small mammals, and other fish up to its own body length; the speed of the strike is among the fastest of any freshwater fish', notes:'the muskellunge (E. masquinongy) is the largest member of the family, reaching 1.8 m; E. lucius (northern pike) is one of the most widely distributed freshwater predators on Earth, present across boreal North America, Europe, and Asia; considered sacred in some Nordic mythology' },

  // â”€â”€ Marine: Misc â”€â”€
  'Caesio':         { fam:'Caesionidae', type:'fusilier', habitat:'open water above coral reefs of the Indo-Pacific, typically 5â€“40 m', feeding:'zooplanktivore; forms enormous fast-swimming schools in open water above reef drop-offs, sweeping copepods and small crustaceans from the current', notes:'fusiliers are critical prey fish in reef ecosystems; the constant open-water schooling provides food for large pelagic predators (tunas, jacks, sharks) that are drawn to reefs by fusilier aggregations' },
  'Cephalopholis':  { fam:'Serranidae', type:'grouper / coral hind', habitat:'coral reefs, tropical Indo-Pacific and Rea Sea, 1â€“40 m', feeding:'piscivore; lies near cover and lunges with a suction-strike throat expansion to engulf passing fish', behavior:'territorial; solitary; protogynous hermaphrodite', notes:'the coral hind (C. miniata) is one of the most iconic groupers of the Indo-Pacific' },
  'Pterois':        { fam:'Scorpaenidae', type:'lionfish', habitat:'coral reefs, rocky reefs, and mangroves of the Indo-Pacific; invasive in the Atlantic', feeding:'ambush predator; uses the spread of pectoral fins to herd small fish into a corner before consuming them in a single engulf; venom in spines used defensively', behavior:'largely nocturnal; remarkably bold for a venomous fish; will confront rather than flee threatening animals', notes:'the Indo-Pacific lionfish (P. volitans and P. miles) were introduced to the Atlantic/Caribbean in the 1980sâ€“90s via aquarium releases; they have caused catastrophic ecological damage to Caribbean and Gulf of Mexico reefs with no natural predators; estimated to consume 80% of native reef fish in some areas; one of the most damaging marine invasive species in history' },
  'Hippocampus':    { fam:'Syngnathidae', type:'seahorse' },  // duplicate handled above, skip
  'Taeniura':       { fam:'Dasyatidae', type:'stingray', habitat:'sandy and rubble areas of Indo-Pacific reefs and lagoons, 1â€“30 m', feeding:'predator of invertebrates buried in sand; uses electroreceptors (ampullae of Lorenzini) to detect the electrical fields of buried prey', behavior:'rests partially buried in sand during the day; the venomous tail spine is used defensively when stepped on or handled', notes:'T. lymma (blue-spotted stingray) is one of the most recognizable rays of the Indo-Pacific; the blue spots are aposematic â€” warning coloration signaling the venomous spine; tail spine injuries to waders are common in areas where the species rests on intertidal flats' },
  'Flowerhorn':     { fam:'Cichlidae', type:'hybrid ornamental cichlid', habitat:'does not exist in nature; entirely man-made', feeding:'omnivorous carnivore', notes:'Flowerhorn cichlids are entirely artificial hybrids developed in Malaysia and Taiwan in the late 1990s by crossing South American and Central American cichlids; key progenitor species include Vieja melanura and Amphilophus trimaculatus; the nuchal hump (kok) is selectively bred to be extraordinarily large and is associated with fortune in Chinese culture (resembling the head of the god of longevity); the fish has no wild counterpart and is considered an iconic example of extreme selective breeding in ornamental fish' },
  'Delphinus':      { fam:'Delphinidae', type:'dolphin', habitat:'open ocean, worldwide in tropical to temperate seas', feeding:'schooling fish and squid; hunts cooperatively in pods; uses echolocation to detect prey', notes:'Delphinus tropicalis (Indo-Pacific common dolphin) included in the collection as one of its non-fish marine animals; listed as Least Concern by IUCN but critically important as an indicator of pelagic ecosystem health; pods of hundreds recorded in the Indian Ocean' },
};

// â”€â”€ Locality habitat context (supplements genus text) â”€â”€
const LOCALITY_CONTEXT = {
  'Lake Malawi':   'a Rift Valley lake in East Africa â€” the world\'s ninth-largest, 560 km long, and home to approximately 1,000 species of cichlid fish, more than any comparable freshwater body on Earth',
  'Lake Tanganyika':'the world\'s second-deepest lake and oldest of the African Great Rift Valley lakes; at 673 m deep it has an oxic zone only in the top 200 m; its extraordinary age (9â€“12 million years) allowed cichlids to diversify into 250+ endemic species',
  'Lake Victoria': 'the world\'s largest tropical lake and second-largest freshwater lake by area; home to the most rapid vertebrate radiation in evolutionary history; the introduction of Nile perch in the 1950s caused 200+ cichlid extinctions',
  'Red Sea':       'arguably the world\'s most fish-rich body of water per unit area; an enclosed sea connected to the Indian Ocean by the narrow Bab-el-Mandeb Strait; its enclosed geography led to the evolution of many endemic species; water temperatures regularly exceed 30Â°C',
  'Amazon River':  'the world\'s largest river by discharge volume, draining 40% of South America; its blackwater and clearwater tributaries host over 3,000 species of freshwater fish, the most diverse freshwater fish fauna on Earth',
  'Orinoco':       'the Orinoco River basin of Venezuela and Colombia, sharing many species with the Amazon but with significant unique endemism in its headwaters; seasonally flooded llanos are critical habitat for many species',
  'Raja Ampat':    'an archipelago in West Papua, Indonesia, considered the global center of marine biodiversity; contains more reef fish species per square meter than any other documented site on Earth',
  'Coral Triangle': 'a marine region encompassing the Philippines, Indonesia, Malaysia, Papua New Guinea, Solomon Islands, and Timor-Leste â€” the center of marine biodiversity, with 600+ coral species and 2,000+ reef fish species',
};

// â”€â”€ Build a rich contextual bio from genus knowledge + fish data â”€â”€
function buildFallbackBio(f) {
  const g   = GENUS_ECOLOGY[f.genus] || {};
  const loc = f.locality || '';
  const statusCode = f.status || '?';
  const statusName = (typeof STATUS_NAMES !== 'undefined' ? STATUS_NAMES[statusCode] : null) || statusCode;
  const genusCount = (typeof FISH_DATA !== 'undefined') ? FISH_DATA.filter(x => x.genus === f.genus).length : 0;
  const locCount   = (typeof FISH_DATA !== 'undefined' && loc) ? FISH_DATA.filter(x => x.locality === loc).length : 0;

  const parts = [];

  // Opening: species identity
  if (f.genus && f.species && f.species !== '') {
    const speciesEtym = buildSpeciesNote(f.species);
    parts.push(`<p class="detail-prose"><em>${f.genus} ${f.species}</em>${f.name ? ' â€” commonly known as the <strong>' + escapeHTML(f.name) + '</strong>' : ''} â€” is a member of the family <strong>${g.fam || 'Teleostei'}</strong>${g.type ? ', specifically a ' + g.type : ''}.${speciesEtym ? ' ' + speciesEtym : ''}</p>`);
  }

  // Habitat + ecology
  if (g.habitat) {
    let habitatText = `<p class="detail-prose">This species inhabits ${g.habitat}.`;
    if (g.depth) habitatText += ` Typical depth range is ${g.depth}.`;
    if (loc) {
      // Add locality context if we know something about it
      const locKey = Object.keys(LOCALITY_CONTEXT).find(k => loc.toLowerCase().includes(k.toLowerCase()));
      if (locKey) habitatText += ` Its locality of <strong>${escapeHTML(loc)}</strong> is within ${LOCALITY_CONTEXT[locKey]}.`;
      else habitatText += ` The recorded locality for this individual is <strong>${escapeHTML(loc)}</strong>.`;
    }
    habitatText += '</p>';
    parts.push(habitatText);
  } else if (loc) {
    parts.push(`<p class="detail-prose">This specimen was recorded from <strong>${escapeHTML(loc)}</strong>.${locCount > 1 ? ` A total of ${locCount} CryptoFish in the collection originate from this locality.` : ''}</p>`);
  }

  // Feeding + behavior
  if (g.feeding) {
    parts.push(`<p class="detail-prose">Feeding ecology: ${g.feeding}.</p>`);
  }
  if (g.behavior) {
    parts.push(`<p class="detail-prose">${g.behavior}.</p>`);
  }

  // Genus context
  if (genusCount > 1 && f.genus) {
    parts.push(`<p class="detail-prose bio-genus-note">The genus <em>${escapeHTML(f.genus)}</em> is represented by <strong>${genusCount} tokens</strong> in the CryptoFish collection, reflecting the extraordinary species diversity within this group.${g.notes ? ' ' + g.notes + '.' : ''}</p>`);
  } else if (g.notes) {
    parts.push(`<p class="detail-prose bio-genus-note">${g.notes}.</p>`);
  }

  // If we have nothing meaningful, give a basic note
  if (parts.length === 0) {
    parts.push(`<p class="detail-prose"><em>${escapeHTML(f.sci || f.name)}</em> â€” each token in the CryptoFish collection represents a real species researched and illustrated by Findurnemo using scientific databases including FishBase and the IUCN Red List.</p>`);
  }

  return parts.join('');
}

function buildSpeciesNote(species) {
  // Try to derive meaning from species epithet - Latin/Greek descriptors
  const notes = {
    'volitans':    'The species epithet <em>volitans</em> means "flying" in Latin, referring to the sweeping pectoral fins.',
    'aurantiacus': 'The epithet <em>aurantiacus</em> is Latin for "orange-colored."',
    'nigricans':   'The epithet <em>nigricans</em> means "becoming black" or "darkening" in Latin.',
    'bicolor':     'The epithet <em>bicolor</em> means "two-colored" in Latin.',
    'tricolor':    'The epithet <em>tricolor</em> means "three-colored" in Latin.',
    'lineatus':    'The epithet <em>lineatus</em> means "lined" or "striped" in Latin.',
    'fasciatus':   'The epithet <em>fasciatus</em> means "banded" or "striped" in Latin.',
    'maculatus':   'The epithet <em>maculatus</em> means "spotted" in Latin.',
    'zebra':       'The epithet <em>zebra</em> references the strongly banded striped pattern.',
    'moorii':      'The species was named in honor of naturalist John Moore, who collected specimens on early Lake Tanganyika expeditions.',
    'frontosa':    'The epithet <em>frontosa</em> means "having a large forehead" in Latin, referring to the nuchal hump.',
    'pulcher':     'The epithet <em>pulcher</em> is Latin for "beautiful."',
    'compressiceps': 'The epithet <em>compressiceps</em> means "compressed head" in Latin, describing the laterally-flattened body.',
    'coeruleus':   'The epithet <em>coeruleus</em> is Latin for "sky blue" or "deep blue."',
    'magnificus':  'The epithet <em>magnificus</em> is Latin for "magnificent" or "splendid."',
    'ocellatus':   'The epithet <em>ocellatus</em> means "bearing eye-spots" in Latin.',
    'hepatus':     'The epithet <em>hepatus</em> means "liver-colored" in Greek, referring to the brown body.',
    'auratus':     'The epithet <em>auratus</em> means "gilded" or "golden" in Latin.',
  };
  const key = Object.keys(notes).find(k => species.toLowerCase().includes(k));
  return key ? notes[key] : '';
}

// â”€â”€ Build honorary bio HTML â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
function buildHonoraryBio(handle) {
  const bio = HONORARY_BIOS[handle];
  if (bio) {
    return `<p class="detail-prose">${escapeHTML(bio)}</p>
    <p class="detail-prose bio-genus-note">Honorary tokens are hand-issued directly by Findurnemo as personal acknowledgments. They are not part of the open minting process and cannot be replicated â€” each one is genuinely unique in the collection.</p>`;
  }
  return `<p class="detail-prose">This is a personal honorary token created by Findurnemo for <strong>${escapeHTML(handle)}</strong>, in recognition of their contribution to the CryptoFish community.</p>
    <p class="detail-prose bio-genus-note">Honorary tokens are hand-issued directly by Findurnemo and are completely unique. They do not follow the standard species classification system â€” they are personal tributes.</p>`;
}

// â”€â”€ Main entry: fetch bio for a fish object â”€â”€â”€â”€â”€â”€â”€â”€
async function fetchFishBio(f) {
  // Pure honorary (no genus/species)
  if (f.honorary && !f.genus) {
    return { html: buildHonoraryBio(f.honorary), wiki: null };
  }

  const cacheKey = f.sci || f.name;
  if (_bioCache.has(cacheKey)) return _bioCache.get(cacheKey);

  let result = null;

  // Try Wikipedia REST API (CORS-enabled, no key needed)
  if (f.genus && f.species && f.species.trim() !== '') {
    try {
      const speciesSlug = encodeURIComponent((f.genus + '_' + f.species).replace(/ /g, '_'));
      const r = await fetch(
        `https://en.wikipedia.org/api/rest_v1/page/summary/${speciesSlug}`,
        { cache: 'force-cache', signal: AbortSignal.timeout(5000) }
      );
      if (r.ok) {
        const d = await r.json();
        if (d.type === 'standard' && d.extract && d.extract.length > 120) {
          // Split into paragraphs if the extract has multiple natural paragraphs
          const paragraphs = d.extract.split('\n').filter(p => p.trim().length > 40);
          const html = paragraphs.map(p => `<p class="detail-prose">${escapeHTML(p)}</p>`).join('') +
            (d.content_urls?.desktop?.page
              ? `<a class="wiki-link" href="${d.content_urls.desktop.page}" target="_blank" rel="noopener noreferrer">Read full article on Wikipedia â† - </a>`
              : '');
          result = { html, wiki: d.content_urls?.desktop?.page || null };
        }
      }
    } catch (_) { /* timeout or network error â€” fall through to fallback */ }
  }

  // Fall back to rich genus-based bio
  if (!result) {
    result = { html: buildFallbackBio(f), wiki: null };
  }

  _bioCache.set(cacheKey, result);
  return result;
}

