// ================================================
// CryptoFish — data.js
// Fish, locality, sales data + generators
// ================================================

const FISH_DATA = [
  { id:'0001', emoji:'🐠', common:'Clownfish (Ocellaris)', sci:'Amphiprion ocellaris', order:'Perciformes', family:'Pomacentridae', genus:'Amphiprion', species:'ocellaris', locality:'Indo-Pacific', status:'LC', price:'0.064', history:'The Ocellaris Clownfish is one of the most recognizable coral reef fish in the world, famous for its mutualistic relationship with sea anemones. It shelters among the stinging tentacles of its host anemone — a coating of mucus protects it from what would be lethal to most other fish. Found throughout the Indo-Pacific from the eastern Indian Ocean to northwest Australia and southeast Asia.', conservation:'Currently classified as Least Concern by the IUCN, the Ocellaris Clownfish maintains stable wild populations. However, the coral reef habitats it depends on are under increasing threat from ocean warming, bleaching events, and ocean acidification. The popularity of this species following cultural attention has also driven substantial collection pressure for the aquarium trade.' },
  { id:'0847', emoji:'🦁', common:'Lionfish', sci:'Pterois volitans', order:'Scorpaeniformes', family:'Scorpaenidae', genus:'Pterois', species:'volitans', locality:'Indo-Pacific', status:'VU', price:'0.12', history:'The Red Lionfish is one of the most visually striking predators in the ocean — its elaborate fan-like pectoral fins and bold striped pattern serving as both camouflage and warning. Its dorsal spines deliver a potent venom capable of causing extreme pain in humans. Native to the tropical Indo-Pacific, it has become one of the most damaging marine invasive species in the Atlantic and Caribbean.', conservation:'In its native range the Lionfish is classified as Vulnerable. In the Atlantic and Caribbean, where it was introduced by the aquarium trade, it has no natural predators and reproduces rapidly, devastating local reef fish populations. Its invasive presence is now considered one of the most urgent marine conservation challenges in the Western Atlantic.' },
  { id:'1204', emoji:'🦈', common:'Zebra Shark', sci:'Stegostoma tigrinum', order:'Orectolobiformes', family:'Stegostomatidae', genus:'Stegostoma', species:'tigrinum', locality:'Coral Sea', status:'EN', price:'0.22', history:'The Zebra Shark is named for the bold stripes of its juvenile stage — which fade to spots as it matures, frequently causing confusion with the Leopard Shark. Highly distinctive with a long tail nearly as long as its body, it is a slow, docile species that rests motionless on sandy seafloors during the day, hunting for mollusks and crustaceans at night.', conservation:'Listed as Endangered, the Zebra Shark faces severe pressure from targeted fishing and bycatch across its Indo-Pacific range. Population declines of over 50% have been recorded across parts of its range in recent decades. Coral Sea populations have shown some resilience within marine protected areas.' },
  { id:'0312', emoji:'🐡', common:'Dog-Faced Pufferfish', sci:'Arothron nigropunctatus', order:'Tetraodontiformes', family:'Tetraodontidae', genus:'Arothron', species:'nigropunctatus', locality:'Red Sea', status:'LC', price:'0.07', history:'The Dog-Faced Pufferfish is a robust, round-bodied species with a distinctly dog-like face — large eyes, a blunt snout, and a wide mouth built for crushing hard-shelled invertebrates. Like all pufferfish, it can rapidly inflate its body with water when threatened. Its skin and organs contain tetrodotoxin, one of the most potent biological toxins known to science.', conservation:'Classified as Least Concern, the Dog-Faced Pufferfish is widely distributed across the Indo-Pacific and Red Sea. It is collected for the aquarium trade and occasionally targeted by subsistence fishers, though its tetrodotoxin content provides some protection from consumption. Reef degradation remains the primary long-term threat to its habitat.' },
  { id:'1891', emoji:'🐙', common:'Greater Blue-Ringed Octopus', sci:'Hapalochlaena lunulata', order:'Octopoda', family:'Octopodidae', genus:'Hapalochlaena', species:'lunulata', locality:'Great Barrier Reef', status:'LC', price:'0.09', history:'Among the most venomous marine animals on Earth, the Greater Blue-Ringed Octopus displays over 60 iridescent blue rings as a warning signal when threatened. Despite its small size — typically 5–8 cm — it carries enough tetrodotoxin to kill 26 adult humans. Found in tide pools and shallow reef flats throughout the Pacific and Indian Oceans.', conservation:'Despite its fearsome reputation, the Blue-Ringed Octopus is classified as Least Concern. Its cryptic lifestyle and wide distribution have buffered it from major population declines. The primary threats are habitat loss in shallow reef and tidal flat ecosystems, as well as collection for the curio trade — which is illegal in several countries due to its extreme toxicity.' },
  { id:'0057', emoji:'🐋', common:'Blue Whale', sci:'Balaenoptera musculus', order:'Artiodactyla', family:'Balaenopteridae', genus:'Balaenoptera', species:'musculus', locality:'Global Oceans', status:'EN', price:'12.5', history:'The largest animal ever known to have existed, the Blue Whale reaches lengths of up to 33 meters and weights exceeding 180 tonnes. Its heart alone can weigh as much as a car. Despite its immense size, it feeds almost exclusively on krill — consuming up to 4 tonnes per day during feeding season. Its low-frequency calls are among the loudest sounds produced by any animal.', conservation:'Classified as Endangered, Blue Whale populations were devastated by commercial whaling in the 20th century, with global numbers reduced to an estimated 1–3% of pre-whaling levels. While the 1986 international whaling moratorium has allowed slow recovery, current threats include ship strikes, entanglement in fishing gear, noise pollution, and prey depletion from climate-driven krill decline.' },
  { id:'0003', emoji:'🪸', common:'West Indian Ocean Coelacanth', sci:'Latimeria chalumnae', order:'Coelacanthiformes', family:'Latimeriidae', genus:'Latimeria', species:'chalumnae', locality:'Comoro Islands', status:'CR', price:'8.8', history:'The Coelacanth is often called a "living fossil" — a lineage thought to have gone extinct 66 million years ago until a living specimen was discovered off South Africa in 1938. It belongs to a group more closely related to lungfish and tetrapods than to most modern fish. It swims using paired lobe fins in an alternating pattern resembling the limb movement of land animals.', conservation:'Critically Endangered, the West Indian Ocean Coelacanth has an estimated global population of fewer than 1,000 individuals, concentrated around the Comoro Islands, Tanzania, Mozambique, and South Africa. Extremely sensitive to bycatch, it is caught accidentally in deep-set shark lines and gill nets. Its small, fragmented population and slow reproductive rate make it highly vulnerable to extinction.' },
  { id:'0721', emoji:'🐬', common:'Spinner Dolphin', sci:'Stenella longirostris', order:'Artiodactyla', family:'Delphinidae', genus:'Stenella', species:'longirostris', locality:'Hawaiian Waters', status:'LC', price:'6.2', history:'The Spinner Dolphin is named for its spectacular acrobatic leaps in which it spins on its longitudinal axis — sometimes completing 7 rotations in a single leap. Found throughout tropical and subtropical waters worldwide, it is highly social, traveling in schools of up to 1,000 individuals. It rests in shallow coastal bays during the day and moves to deeper offshore waters to feed at night.', conservation:'Classified as Least Concern globally, Spinner Dolphin populations face localized pressure from disturbance in critical resting bays — particularly from unregulated dolphin-watching tourism in Hawaii and other locations where boats follow resting pods.' },
  { id:'0445', emoji:'🐟', common:'Regal Blue Tang', sci:'Paracanthurus hepatus', order:'Perciformes', family:'Acanthuridae', genus:'Paracanthurus', species:'hepatus', locality:'Indo-Pacific', status:'LC', price:'0.08', history:'The Regal Blue Tang is immediately recognizable by its vivid royal blue body, black palette marking, and yellow tail. One of the most widespread surgeonfish in the Indo-Pacific, it grazes on algae growing on coral reef surfaces, playing a crucial role in preventing algal overgrowth that would otherwise smother corals.', conservation:'Listed as Least Concern, the Regal Blue Tang is abundant across its wide range. The aquarium trade has dramatically intensified collection pressure. Unlike clownfish, the Regal Blue Tang has not yet been reliably bred in captivity at commercial scale, meaning virtually all specimens in the trade are wild-caught.' },
  { id:'0988', emoji:'🦭', common:'Hawaiian Monk Seal', sci:'Neomonachus schauinslandi', order:'Carnivora', family:'Phocidae', genus:'Neomonachus', species:'schauinslandi', locality:'Hawaiian Waters', status:'EN', price:'0.45', history:'The Hawaiian Monk Seal is one of the most endangered marine mammals on Earth, and one of only two remaining monk seal species. Endemic to the Hawaiian archipelago, it is one of the oldest seal species — a true "living fossil" of the phocid family. It is the only seal native to the tropics, hunting fish, eels, octopus, and crustaceans in the shallow waters and coral reefs of the Hawaiian Islands.', conservation:'Classified as Endangered, the Hawaiian Monk Seal population is estimated at approximately 1,400 individuals. Key threats include entanglement in fishing gear, prey depletion, shark predation on juveniles, habitat loss, and marine debris ingestion. Intensive conservation programs by NOAA have helped stabilize but not yet reverse the population decline.' },
  { id:'0622', emoji:'🦑', common:'Humboldt Squid', sci:'Dosidicus gigas', order:'Teuthida', family:'Ommastrephidae', genus:'Dosidicus', species:'gigas', locality:'Pacific Ocean', status:'LC', price:'0.068', history:'The Humboldt Squid reaches up to 2 meters in length and 50 kg. It hunts in coordinated groups, using bioluminescence to communicate and coordinate attacks on prey. Its tentacles bear sharp, toothed suckers capable of leaving permanent scars on prey and handlers alike.', conservation:'Classified as Least Concern, the Humboldt Squid is highly abundant in the eastern Pacific, particularly in the Humboldt Current upwelling system. Climate change and ocean warming are causing range expansions northward into Alaskan waters, with cascading effects on local food webs and fishing industries.' },
  { id:'1344', emoji:'🦐', common:'Banded Coral Shrimp', sci:'Stenopus hispidus', order:'Decapoda', family:'Stenopodidae', genus:'Stenopus', species:'hispidus', locality:'Caribbean', status:'LC', price:'0.065', history:'The Banded Coral Shrimp operates as a "cleaner shrimp," removing parasites, dead tissue, and debris from fish that approach its territory. This cleaning behavior is one of the most extraordinary mutualistic relationships on the reef.', conservation:'Listed as Least Concern, the Banded Coral Shrimp is widely distributed across tropical reef environments globally. It is heavily collected for the marine aquarium trade, where it remains one of the most popular invertebrate species. Coral reef degradation poses the primary threat.' },
  { id:'0199', emoji:'🐚', common:'Chambered Nautilus', sci:'Nautilus pompilius', order:'Nautilida', family:'Nautilidae', genus:'Nautilus', species:'pompilius', locality:'Coral Sea', status:'VU', price:'0.18', history:'The Chambered Nautilus is one of the most ancient animal designs still in existence — its shell architecture unchanged for hundreds of millions of years. It uses a series of gas-filled chambers to regulate buoyancy, rising and descending through hundreds of meters of water daily in vertical migrations.', conservation:'Listed as Vulnerable, the Chambered Nautilus faces significant pressure from the shell trade. Its beautiful spiral shell is harvested on a massive scale for jewelry and tourist markets across the Indo-Pacific. The species reproduces extremely slowly, making populations highly sensitive to harvest pressure.' },
  { id:'0776', emoji:'🦞', common:'Caribbean Spiny Lobster', sci:'Panulirus argus', order:'Decapoda', family:'Palinuridae', genus:'Panulirus', species:'argus', locality:'Caribbean', status:'LC', price:'0.072', history:'The Caribbean Spiny Lobster undertakes one of the most remarkable animal migrations in the ocean — forming single-file queues of hundreds of individuals that march in formation across the seafloor for days, navigating by Earth\'s magnetic field.', conservation:'Currently classified as Least Concern, the Caribbean Spiny Lobster supports economically vital fisheries from Florida through the Caribbean. Some regional populations show signs of overexploitation, particularly in areas without robust management.' },
  { id:'1567', emoji:'🦀', common:'Sally Lightfoot Crab', sci:'Grapsus grapsus', order:'Decapoda', family:'Grapsidae', genus:'Grapsus', species:'grapsus', locality:'Galápagos Islands', status:'LC', price:'0.066', history:'The Sally Lightfoot Crab is one of the most brilliantly colored crustaceans in the world — its adult carapace blazing in reds and oranges with blue and green highlights. Named for its extraordinary agility, it can run in any direction and leap between rocks with remarkable precision.', conservation:'Listed as Least Concern, the Sally Lightfoot Crab is abundant throughout its range. Climate events affecting the Galápagos ecosystem, particularly El Niño cycles, can cause localized population crashes.' },
  { id:'0834', emoji:'🐠', common:'Percula Clownfish', sci:'Amphiprion percula', order:'Perciformes', family:'Pomacentridae', genus:'Amphiprion', species:'percula', locality:'Solomon Islands', status:'LC', price:'0.068', history:'The Percula Clownfish is the true clownfish of the Solomon Islands and adjacent Melanesian waters. Nearly identical to the Ocellaris Clownfish in appearance, it can be distinguished by its thicker black borders around the white stripes and its association with specific anemone hosts including Heteractis magnifica.', conservation:'Classified as Least Concern with stable populations, the Percula Clownfish is subject to intense aquarium trade collection, particularly in the Solomon Islands and Papua New Guinea. Sea anemone population decline due to coral bleaching poses an existential habitat threat.' },
  { id:'1102', emoji:'🐟', common:'Yellowfin Tuna', sci:'Thunnus albacares', order:'Perciformes', family:'Scombridae', genus:'Thunnus', species:'albacares', locality:'Global Oceans', status:'NT', price:'0.09', history:'The Yellowfin Tuna is a warm-blooded, endothermic fish capable of sustained speeds exceeding 75 km/h. Its distinctive bright yellow dorsal and anal fins are unmistakable. It is one of the most commercially valuable fish in the global fishing industry.', conservation:'Currently Near Threatened, Yellowfin Tuna populations are under significant pressure from industrial purse seine and longline fisheries throughout the tropics. The use of Fish Aggregating Devices has dramatically increased bycatch of juvenile tunas and non-target species.' },
  { id:'0543', emoji:'🐟', common:'Humphead Wrasse', sci:'Cheilinus undulatus', order:'Perciformes', family:'Labridae', genus:'Cheilinus', species:'undulatus', locality:'Red Sea', status:'EN', price:'0.28', history:'The Humphead Wrasse — also called the Napoleon Fish — is the largest member of the wrasse family, reaching up to 2 meters and 190 kg. It is one of the few predators capable of eating toxic prey including crown-of-thorns starfish, boxfish, and sea hares, making it ecologically critical on Indo-Pacific reefs.', conservation:'Listed as Endangered, the Humphead Wrasse has suffered catastrophic population declines due to targeted spear fishing and collection for the live reef fish food trade across Southeast Asia, where it commands premium prices in high-end restaurants.' },
  { id:'0289', emoji:'🦈', common:'Whale Shark', sci:'Rhincodon typus', order:'Orectolobiformes', family:'Rhincodontidae', genus:'Rhincodon', species:'typus', locality:'Indo-Pacific', status:'EN', price:'0.38', history:'The Whale Shark is the largest fish on Earth, reaching verified lengths of over 18 meters. Despite its immense size, it is a filter feeder — swimming slowly through plankton-rich waters with its mouth agape, filtering enormous volumes of water.', conservation:'Classified as Endangered, Whale Shark populations have declined by over 50% in recent decades primarily due to targeted hunting for their fins and meat, bycatch in trawl fisheries, and boat strikes.' },
  { id:'1789', emoji:'🐟', common:'Moorish Idol', sci:'Zanclus cornutus', order:'Perciformes', family:'Zanclidae', genus:'Zanclus', species:'cornutus', locality:'Indo-Pacific', status:'LC', price:'0.075', history:'The Moorish Idol is one of the most distinctively shaped reef fish — its dramatic triangular body, long trailing dorsal filament, and bold black, white, and yellow banding make it immediately recognizable. It is the sole member of its family, Zanclidae, with no close living relatives.', conservation:'Classified as Least Concern with abundant and stable populations, the Moorish Idol has the unfortunate distinction of being extremely difficult to maintain in captivity — it rarely survives the transition to artificial environments and rarely accepts prepared foods.' },
  { id:'0667', emoji:'🐟', common:'Mandarinfish', sci:'Synchiropus splendidus', order:'Perciformes', family:'Callionymidae', genus:'Synchiropus', species:'splendidus', locality:'Coral Sea', status:'LC', price:'0.095', history:'The Mandarinfish is widely considered one of the most beautiful fish in the ocean — its intricate pattern of electric blue, orange, and green psychedelic swirls covering every surface of its small body. Unusually, its coloration is produced not by chromatophores but by cyanophores — cells containing a blue pigment rare in vertebrates.', conservation:'Listed as Least Concern globally but declining in collection-intensive areas, the Mandarinfish faces heavy pressure from the marine aquarium trade despite its poor survival rate in captivity. Most wild-caught specimens die within weeks in aquarium conditions due to their highly specialized diet of copepods.' },
  { id:'1423', emoji:'🦈', common:'Scalloped Hammerhead', sci:'Sphyrna lewini', order:'Carcharhiniformes', family:'Sphyrnidae', genus:'Sphyrna', species:'lewini', locality:'Global Oceans', status:'CR', price:'0.52', history:'The Scalloped Hammerhead Shark is instantly recognizable by its distinctively flattened, hammer-shaped head — called a cephalofoil. This extraordinary adaptation improves electroreception, allowing the shark to detect prey buried in sand with remarkable precision. Scalloped Hammerheads are highly social, forming enormous aggregations of hundreds to thousands of individuals at seamounts and offshore islands.', conservation:'Classified as Critically Endangered following decades of catastrophic population decline, Scalloped Hammerhead populations have fallen by 80–99% across their historical range. The primary drivers are targeted fishing for fins and bycatch in tuna and swordfish longline fisheries.' },
  { id:'0901', emoji:'🐠', common:'Copperband Butterflyfish', sci:'Chelmon rostratus', order:'Perciformes', family:'Chaetodontidae', genus:'Chelmon', species:'rostratus', locality:'Great Barrier Reef', status:'LC', price:'0.074', history:'The Copperband Butterflyfish is distinguished by its long, narrow beak-like snout — evolved for extracting small invertebrates and worms from deep crevices in coral and rubble. Its bold orange-copper vertical banding and distinctive false eye spot near the tail fin make it one of the most visually striking butterflyfish.', conservation:'Listed as Least Concern with widespread stable populations, the Copperband Butterflyfish is popular in the aquarium trade due to its striking appearance. It is also one of the few fish known to eat Aiptasia anemones, making it prized for reef aquarium pest control.' },
  { id:'1678', emoji:'🦈', common:'Nurse Shark', sci:'Ginglymostoma cirratum', order:'Orectolobiformes', family:'Ginglymostomatidae', genus:'Ginglymostoma', species:'cirratum', locality:'Caribbean', status:'VU', price:'0.15', history:'The Nurse Shark is largely sedentary during daylight hours, resting in groups on sandy bottoms and in caves, often piled atop each other. It uses powerful suction to pull invertebrates from crevices, and is one of the few sharks capable of resting motionless on the seafloor while breathing.', conservation:'Listed as Vulnerable, Nurse Shark populations have declined in heavily fished areas. Their shallow, coastal habitat makes them particularly vulnerable to reef degradation and fishing pressure. They are frequently encountered by divers and are generally docile, but handling can provoke a tenacious bite.' },
];

const PLACEHOLDER_EMOJIS = ['🐟','🐠','🐡','🦈','🐙','🦑','🦐','🦞','🦀','🐚','🦭','🐬'];
const PLACEHOLDER_NAMES  = ['Pacific Tang','Foxface Rabbitfish','Clarkii Clownfish','Royal Dottyback','Tailspot Blenny','Firefish Goby','Mandarin Dragonet','Coral Beauty','Flame Angelfish','Lemon Damsel','Purple Tang','Bicolor Goatfish','Sixline Wrasse','Neon Goby','Orchid Dottyback','Tomini Tang','Spotted Cardinalfish','Antenna Goby','Falco Hawkfish','Dragon Goby'];
const PLACEHOLDER_GENERA = ['Acanthurus','Siganus','Amphiprion','Pseudochromis','Ecsenius','Nemateleotris','Synchiropus','Centropyge','Chrysiptera','Mulloidichthys'];
const PLACEHOLDER_LOCS   = ['Red Sea','Caribbean','Great Barrier Reef','Coral Sea','Indo-Pacific','Solomon Islands','Hawaiian Waters'];
const PLACEHOLDER_STATUSES = ['LC','LC','LC','LC','NT','VU','EN','LC','NT','LC'];

function generatePlaceholders(count, offset) {
  return Array.from({ length: count }, (_, i) => {
    const idx = i + offset;
    return {
      id:       String(2000 + idx).padStart(4, '0'),
      emoji:    PLACEHOLDER_EMOJIS[idx % PLACEHOLDER_EMOJIS.length],
      common:   PLACEHOLDER_NAMES[idx % PLACEHOLDER_NAMES.length],
      sci:      PLACEHOLDER_GENERA[idx % PLACEHOLDER_GENERA.length] + ' sp.',
      order:    'Perciformes', family: 'Pomacentridae',
      genus:    PLACEHOLDER_GENERA[idx % PLACEHOLDER_GENERA.length],
      species:  'sp.',
      locality: PLACEHOLDER_LOCS[idx % PLACEHOLDER_LOCS.length],
      status:   PLACEHOLDER_STATUSES[idx % PLACEHOLDER_STATUSES.length],
      price:    (0.064 + idx * 0.003).toFixed(3),
      history:  'A stunning reef species found across Indo-Pacific coral ecosystems. Full species data available in the complete collection on-chain metadata.',
      conservation: 'Full conservation notes for this species are encoded in the on-chain metadata. Please refer to the IUCN Red List for the current population assessment.',
    };
  });
}

const LOCALITIES = [
  { name:'Indo-Pacific',       sub:'Indian Ocean to Pacific Ocean',         count:412, lat:10,   lon:120,  color:'#2d7a4f', fish:['🐠','🦁','🦈','🦑'], desc:'The Indo-Pacific region is the most biodiverse marine environment on Earth, containing the Coral Triangle — the global center of marine biodiversity.' },
  { name:'Great Barrier Reef', sub:'Queensland, Australia',                 count:284, lat:-18,  lon:148,  color:'#2d7a4f', fish:['🐙','🦈','🐟','🐠'], desc:'The world\'s largest coral reef system — stretching over 2,300 km along the northeast coast of Australia. A UNESCO World Heritage Site, home to over 1,500 species of fish.' },
  { name:'Red Sea',            sub:'Northeast Africa & Arabian Peninsula',  count:198, lat:22,   lon:38,   color:'#7a6d2d', fish:['🐡','🦐','🦈','🐟'], desc:'One of the world\'s most saline bodies of water, the Red Sea contains over 1,200 species of fish with approximately 10% found nowhere else.' },
  { name:'Caribbean',          sub:'Western Atlantic',                      count:176, lat:17,   lon:-70,  color:'#7a4a2d', fish:['🐠','🦈','🐬','🦞'], desc:'The Caribbean Sea\'s reefs support extraordinary diversity, including over 65 species of stony coral, 500 species of fish, and thousands of invertebrate species.' },
  { name:'Coral Sea',          sub:'Southwest Pacific Ocean',               count:142, lat:-20,  lon:155,  color:'#7a2d2d', fish:['🦈','🐋','🪸','🐚'], desc:'The Coral Sea borders Australia, Papua New Guinea, the Solomon Islands, and New Caledonia — home to extraordinary marine life diversity.' },
  { name:'Hawaiian Waters',    sub:'North Pacific Ocean, USA',              count:118, lat:21,   lon:-157, color:'#2d7a4f', fish:['🐬','🦭','🦈','🐟'], desc:'Hawaii\'s isolation in the central Pacific has produced one of the highest rates of marine endemism in the world — roughly 25% of Hawaiian reef fish are found nowhere else.' },
  { name:'Solomon Islands',    sub:'Melanesia, South Pacific',              count:96,  lat:-9,   lon:160,  color:'#2d7a4f', fish:['🐠','🦑','🐡','🦐'], desc:'The Solomon Islands sits at the heart of the Coral Triangle. Its waters support over 1,000 species of reef fish and 494 species of coral — among the highest densities on Earth.' },
  { name:'Comoro Islands',     sub:'Indian Ocean, East Africa',             count:24,  lat:-12,  lon:44,   color:'#5c1515', fish:['🪸','🦈','🐟','🦑'], desc:'Best known to ichthyologists as the primary habitat of the Coelacanth — one of the most remarkable zoological discoveries of the 20th century.' },
  { name:'Galápagos Islands',  sub:'Eastern Pacific, Ecuador',              count:62,  lat:-0.5, lon:-90,  color:'#7a4a2d', fish:['🦀','🦈','🐬','🦭'], desc:'The Galápagos Islands sit at the intersection of three major Pacific ocean currents, creating extraordinary marine diversity and endemism.' },
  { name:'Global Oceans',      sub:'Worldwide Distribution',                count:58,  lat:0,    lon:-30,  color:'#7a2d2d', fish:['🐋','🐬','🦈','🦭'], desc:'Some CryptoFish species have distributions spanning multiple ocean basins — true global travelers: Blue Whales, Yellowfin Tuna, Scalloped Hammerheads.' },
  { name:'Pacific Ocean',       sub:'Largest ocean basin',                    count:86,  lat:5,    lon:-140, color:'#2d7a4f', fish:['🦑','🦈','🐬','🐟'], desc:'The Pacific Ocean is Earth\'s largest and deepest ocean, spanning more area than all landmasses combined. It hosts extraordinary marine diversity from equatorial reefs to polar seas.' },
];

const RECENT_SALES = [
  { fish:'🐠', name:'Percula Clownfish',       token:'#0834', eth:'0.068', usd:'$140',    time:'2m ago',  idx:15 },
  { fish:'🦈', name:'Zebra Shark',             token:'#1204', eth:'0.22',  usd:'$454',    time:'18m ago', idx:2  },
  { fish:'🐡', name:'Dog-Faced Pufferfish',    token:'#0312', eth:'0.07',  usd:'$144',    time:'34m ago', idx:3  },
  { fish:'🐬', name:'Spinner Dolphin',         token:'#0721', eth:'0.085', usd:'$175',    time:'1h ago',  idx:7  },
  { fish:'🪸', name:'Coelacanth',              token:'#0003', eth:'8.8',   usd:'$18,150', time:'3h ago',  idx:6  },
  { fish:'🦁', name:'Lionfish',                token:'#0847', eth:'0.12',  usd:'$247',    time:'5h ago',  idx:1  },
  { fish:'🐙', name:'Blue-Ringed Octopus',     token:'#1891', eth:'0.09',  usd:'$186',    time:'7h ago',  idx:4  },
  { fish:'🦈', name:'Scalloped Hammerhead',    token:'#1423', eth:'0.52',  usd:'$1,074',  time:'9h ago',  idx:21 },
  { fish:'🐟', name:'Humphead Wrasse',         token:'#0543', eth:'0.28',  usd:'$578',    time:'11h ago', idx:17 },
];

const STATUS_NAMES = { LC:'Least Concern', NT:'Near Threatened', VU:'Vulnerable', EN:'Endangered', CR:'Critically Endangered', DD:'Data Deficient' };
const STATUS_COLORS = { LC:'#2d7a4f', NT:'#7a6d2d', VU:'#7a4a2d', EN:'#7a2d2d', CR:'#5c1515', DD:'#555' };
